#!/bin/bash -e

function go_into {
  echo '--------------------------------------------------------------------------------';
  echo "For $1"
  pushd $1 &> /dev/null
}

function go_back {
  popd &> /dev/null
}

function execute_command {
  command=$@
  echo -n "  > "
  echo -en $'\e[33m'"$command"$'\e[0m'

  set +e
  output=$($command 2>&1) 
  error_code=$?
  set -e
  if [ $error_code -eq 0 ]
  then
    echo -n " ["
    echo -n $'\e[32mpass\e[0m'
    echo "]"
  fi

  if [ $error_code -ne 0 ]
  then
    echo -n " ["
    echo -en $'\e[31mfailed\e[0m'
    echo "]"

    echo '********************************************************************************';
    echo "Error:"
    echo 
    echo "$output"
    echo '********************************************************************************';
  fi
}

go_into web
  execute_command npm install
  execute_command bower install
  execute_command karma start karma.conf-ci.js
go_back

go_into user_service
  execute_command bundle
  execute_command RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
  execute_command bundle exec rspec
go_back

go_into auth_service
  execute_command bundle
  execute_command RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
  execute_command bundle exec rspec
go_back

echo
echo "Done"

