default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: asset-management_development

test:
  <<: *default
  database: asset-management_test

production:
  <<: *default
  database: <%= ENV['RAILS_DB_NAME'] %>
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  port: <%= ENV['RAILS_DB_PORT'] %>
  socket: nil

