source 'http://rubygems.org'

gem 'rails', '4.2.1'

gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'faraday', '~> 0.9.2'
gem 'configatron', '~> 4.5.0'
gem 'nokogiri', '~> 1.6.8'

group :production do
  gem 'unicorn', '~> 5.0.0'
end

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'responders', '~> 2.1.0'
  gem 'spring'
end

group :test do
  gem 'webmock', '~> 1.22.3'
  gem 'rspec-rails', '~> 3.4.0'
end

