source 'http://rubygems.org'

gem 'rails', '4.2.1'

gem 'mysql2', '~> 0.3.18'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'

group :production do
  gem 'unicorn', '~> 5.0.0'
end

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.4.0'
  gem 'responders', '~> 2.1.0'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'database_cleaner', '~> 1.5.0'
end

