source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'mysql2', '~> 0.3.18'
gem 'jbuilder', '~> 2.0'

group :production do
  gem 'unicorn', '~> 5.0.0'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.4.0'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'database_cleaner', '~> 1.5.0'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

